export const REJECTION_REASONS = [
  "The selected question is irrelevant or non-academic.",
  "The selected question is relevant but incomplete.",
  "The question is in a language other than English.",
  "The solution is AI-generated and converted using software.",
  "The answer lacks step-by-step explanations.",
  "The final answer or conclusion is not properly mentioned.",
  "The answer is written in red ink.",
  "The answer is not on a white blank page or a white lined page; a colored page is used instead.",
  "The solution is incomplete.",
  "The SME provided an image-based solution.",
  "The SME gave a typed solution.",
  "The answer is not readable, and the handwriting is unclear.",
  "The SME shared direct screenshots from Google.",
  "The SME copied answers from different websites or third-party sources.",
  "The SME provided a one-line solution.",
  "For MCQ-type questions, the SME did not explain why other options are incorrect.",
  "The diagram is not hand-drawn.",
  "The solution is not captured in proper lighting, and there is a shadow over it.",
  "The solution is blurry.",
  "There is student engagement before or after providing the solution.",
  "The shared chat by the SME is not in professional language; casual language is used.",
  "Personal information was exchanged during the doubt session.",
  "The SME forcibly requested to accept the solution.",
];
